import type { TSESLint } from "@typescript-eslint/utils";

/** Arrays and collections. */
export const UNICORN_ARRAYS: TSESLint.FlatConfig.Config = {
  name: "unicorn/arrays",
  rules: {
    "unicorn/consistent-existence-index-check": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/no-array-callback-reference": "error",
    "unicorn/no-array-fill-with-reference-type": "error",
    "unicorn/no-array-from-fill": "error",
    "unicorn/no-array-front-mutation": "error",
    "unicorn/no-array-method-this-argument": "error",
    // `reduce` is the functional fold, required by functional/no-loop-statements.
    "unicorn/no-array-reduce": "off",
    "unicorn/no-array-reverse": "error",
    "unicorn/no-array-sort": "error",
    "unicorn/no-array-splice": "error",
    "unicorn/no-boolean-sort-comparator": "error",
    "unicorn/no-confusing-array-splice": "error",
    "unicorn/no-confusing-array-with": "error",
    "unicorn/no-impossible-length-comparison": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-array-predicate": "error",
    "unicorn/no-new-array": "error",
    "unicorn/no-return-array-push": "error",
    "unicorn/no-unnecessary-array-flat-depth": "error",
    "unicorn/no-unnecessary-array-splice-count": "error",
    "unicorn/no-unnecessary-splice": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-useless-length-check": "error",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-array-from-range": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-last-methods": "error",
    "unicorn/prefer-array-slice": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-flat-math-min-max": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-simple-sort-comparator": "error",
    "unicorn/prefer-single-array-predicate": "error",
    "unicorn/prefer-single-call": "error",
    "unicorn/require-array-join-separator": "error",
    // Duplicate of the type-aware @typescript-eslint/require-array-sort-compare.
    "unicorn/require-array-sort-compare": "off",
  },
};
