import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { defineConfig } from "vitepress";

import type { DefaultTheme } from "vitepress";

/** Base path of the published site (`/SVG-Editor/` on GitHub Pages), `/` locally. */
const BASE = process.env["DOCS_BASE"] ?? "/";

/** Root folder of the documentation site. */
const DOCS_ROOT = join(import.meta.dirname, "..");

/** Sidebar generated by TypeDoc next to the API pages. */
const API_SIDEBAR_FILE = join(DOCS_ROOT, "api", "typedoc-sidebar.json");

/** Name of a folder's index page in the repository (served as the folder's index). */
const FOLDER_INDEX = "README.md";

/** Site sections: title and folder, in reading order. */
const SECTIONS = [
  { folder: "domain", title: "Domain" },
  { folder: "adr", title: "Decisions" },
  { folder: "conventions", title: "Conventions" },
  { folder: "tooling", title: "Tooling" },
  { folder: "derivations", title: "Derivations" },
  { folder: "backlog", title: "Backlog" },
  { folder: "backlog/epics", title: "Epics" },
  { folder: "research", title: "Research" },
];

/**
 * Title of a Markdown page: its first level-1 heading, or its file name.
 *
 * @param path - absolute path of the page
 * @returns text shown in the sidebar for this page
 */
function pageTitle(path: string): string {
  const heading = /^# (?<title>.+)$/mu.exec(readFileSync(path, "utf8"));

  return heading?.groups?.["title"] ?? path;
}

/**
 * Sidebar entries of a section: its index first, then its pages sorted by file name.
 *
 * @param folder - section folder, relative to the docs root
 * @returns sidebar items linking to every Markdown page of the folder
 */
function sectionItems(folder: string): DefaultTheme.SidebarItem[] {
  const pages = readdirSync(join(DOCS_ROOT, folder))
    .filter((name) => name.endsWith(".md") && name !== FOLDER_INDEX && !name.startsWith("_"))
    .toSorted((left, right) => left.localeCompare(right, "en"));

  return pages.map((name) => ({
    link: `/${folder}/${name.slice(0, -".md".length)}`,
    text: pageTitle(join(DOCS_ROOT, folder, name)),
  }));
}

/**
 * Whether a parsed JSON value is a list of sidebar items (TypeDoc's generated sidebar).
 *
 * @param value - parsed JSON
 * @returns `true` for an array of objects with a `text` string
 */
function isSidebar(value: unknown): value is DefaultTheme.SidebarItem[] {
  return (
    Array.isArray(value) &&
    value.every((item: unknown) => typeof item === "object" && item !== null && "text" in item)
  );
}

/**
 * API sidebar generated by TypeDoc, empty before the first `npm run docs:api`.
 *
 * @returns sidebar items of the API reference
 */
function apiItems(): DefaultTheme.SidebarItem[] {
  const parsed: unknown = existsSync(API_SIDEBAR_FILE)
    ? JSON.parse(readFileSync(API_SIDEBAR_FILE, "utf8"))
    : [];

  return isSidebar(parsed) ? parsed : [];
}

/**
 * VitePress configuration of the documentation site.
 *
 * @see docs/tooling/documentation-site.md
 */
export default defineConfig({
  base: BASE,
  cleanUrls: true,
  description: "Integer, orthogonal, path-only SVG editing library for synoptic-view symbols.",
  lang: "en",
  lastUpdated: false,
  srcExclude: ["**/_*.md"],
  rewrites: {
    ":section/:subsection/README.md": ":section/:subsection/index.md",
    ":section/README.md": ":section/index.md",
  },
  themeConfig: {
    nav: [
      ...SECTIONS.map((section) => ({ link: `/${section.folder}/`, text: section.title })),
      { link: "/references", text: "References" },
      { link: "/api/", text: "API" },
    ],
    outline: "deep",
    search: { provider: "local" },
    sidebar: [
      ...SECTIONS.map((section) => ({
        collapsed: false,
        items: [{ link: `/${section.folder}/`, text: "Overview" }, ...sectionItems(section.folder)],
        text: section.title,
      })),
      { items: [{ link: "/references", text: "Bibliography" }], text: "References" },
      { items: [{ link: "/api/", text: "Overview" }, ...apiItems()], text: "API" },
    ],
  },
  title: "editor",
});
